apiVersion: apps/v1
kind: Deployment
metadata:
  name: atd16-demo-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atd16-demo
  template:
    metadata:
      labels:
        app: atd16-demo
    spec:
      containers: 
      - name: atd16-demo-pod
        image: gcr.io/innate-bucksaw-284213/atd16-demo:1.0
        env:
        - name: AZSVC
          value: "Google Kubernetes Engine"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: atd16-demo-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: atd16-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharecare-web-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: gcp.tipuric.com 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: atd16-demo-svc
                port:
                  number: 80
            path: /