apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-demo-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: debug-demo
  template:
    metadata:
      labels:
        app: debug-demo
    spec:
      containers: 
      - name: debug-demo-pod
        image: 996886234804.dkr.ecr.us-east-2.amazonaws.com/debug-demo:88
        env:
        - name: AZSVC
          value: "Elastic Kubernetes Service"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: debug-demo-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: debug-demo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: debug-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: aws.tipuric.com 
    http:
      paths:
      - backend:
          serviceName: debug-demo-svc
          servicePort: 80
        path: /
