apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers: 
      - name: cicd-demo-pod
        image: totipuacr.azurecr.io/hello-cicd:1.0
        env:
        - name: AZSVC
          value: "Azure Kubernetes Service"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: cicd-demo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cicd-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: azure.tipuric.com 
    http:
      paths:
      - backend:
          serviceName: cicd-demo-svc
          servicePort: 80
        path: /
